[package]
name = "mechaia_sound"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
rand = "0.8.5"
symphonia = { version = "0.5.4", features = ["all"] }
util = { path = "../util", package = "mechaia_util" }
glam = "0.27.0"
