[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.27.0"
gltf = { version = "1.4.0", features = ["utils"] }
physics3d = { path = "../physics3d", package = "mechaia_physics3d" }
render = { path = "../render", package = "mechaia_render" }
winit = "0.28"
