[workspace]
resolver = "2"
members = [
	"render",
	"vehicle",
	"terrain",
	"util", "physics3d", "window",
	"mechaia", "gui", "sound", "model",
	"voxel/render", "voxel/common", "input", "script",
]

[profile.dev.package."*"]
opt-level = 3
